import sqlite3

# Connect to the database
conn = sqlite3.connect("jobs.db")
cursor = conn.cursor() # send sql commands to the db, reading results from queries

# List of websites to add (name, url)
websites = [
    ("Google", "https://www.google.com/about/careers/applications/jobs/results?location=Israel"),
    ("Wix", "https://careers.wix.com/positions?locations=tel-aviv%2Cbeer-sheva"),
    ("monday.com", "https://monday.com/careers?location=telaviv"),
    ("Refael", "https://career.rafael.co.il/"),
    ("Elbit", "https://elbitsystemscareer.com/go/%D7%94%D7%A0%D7%93%D7%A1%D7%94-%D7%95%D7%A4%D7%99%D7%AA%D7%95%D7%97/9358855/"),
    ("Mize", "https://mize.tech/careers/"),
    ("Uveye","https://www.uveye.com/careers/"),
    ("Verint", "https://fa-epcb-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX/jobs?location=Israel"),
    ("CheckPoint", "https://careers.checkpoint.com/index.php?q=&module=cpcareers&a=search&fa%5B%5D=country_ss%3AIsrael&sort="),
    ("Thetaray", "https://www.comeet.com/jobs/thetaray/72.00F"),
    ("Earnix", "https://earnix.com/careers-search/?j=&f=%5B%7B%22type%22%3A%22Location%22%2C%22item%22%3A%22Ramat%20Gan%2C%20Israel%22%7D%5D"),
    ("Inmanage", "https://www.inmanage.co.il/%D7%93%D7%A8%D7%95%D7%A9%D7%99%D7%9D"),
    ("Atera", "https://www.atera.com/careers/"),
    ("abra", "https://www.abra-it.com/en/career/"),
    ("eternitech", "https://eternitech.com/jobs/"),
    ("Mend.io", "https://www.mend.io/careers/#positions"),
    ("Zadara", "https://jobs.lever.co/Zadara?location=Tel%20Aviv"),
    ("BMC", "https://jobs.bmc.com/Careers/SearchJobs/?listFilterMode=1&1274=9409&1274_format=1347&intcmp=JobsByCountry"),
    ("VAST", "https://www.vastdata.com/careers#open-positions"),
    ("Cybereason", "https://www.cybereason.com/careers/all-jobs"),
    ("SimilarWeb", "https://www.similarweb.com/corp/careers/#opportunities"),
    ("WalkMe", "https://www.walkme.com/careers/careers_list/"),
    ("Armis", "https://www.armis.com/armis-careers/#discoverjobs"),
    ("Next Insurance", "https://www.nextinsurance.com/careers/#careers"),
    ("Orca Security", "http://orca.security/about/careers/#open-positions"),
    ("Salt Security", "https://salt.security/job-board"),
    ("WSC Sports", "https://wsc-sports.com/careers/"),
    ("Aquant", "https://www.aquant.io/careers/"),
    ("Fundbox", "https://fundbox.com/careers/"),
    ("Melio", "https://careers.meliopayments.com/"),
    ("Tytocare", "https://www.tytocare.com/careers/#openPositionSection"),
    ("Lightricks", "https://careers.lightricks.com/careers?query=&office=Jerusalem&department=all"),
    ("Lightricks", "https://careers.lightricks.com/careers?query=&office=Haifa&department=all"),
    ("Taboola", "https://www.taboola.com/careers/jobs#team=&location=23621"),
    ("Outbrain", "https://www.outbrain.com/careers/"),
    ("Lemonade", "https://makers.lemonade.com/"),
    ("HoneyBook", "https://www.honeybook.com/careers"),
    ("Viber", "https://www.viber.com/en/careers-israel/"),
    ("Kaltura", "https://corp.kaltura.com/company/careers/"),
    ("Tipalti", "https://tipalti.com/company/jobs/"),
    ("BioCatch", "https://www.biocatch.com/cybersecurity-careers"),
    ("Playtika", "https://www.playtika.com/careers/research-development/"),
    ("Playtika", "https://www.playtika.com/careers/analytics/"),
    ("Playtika", "https://www.playtika.com/careers/data-ai/"),
    ("Playtika", "https://www.playtika.com/careers/qa/"),
    ("Playtika", "https://www.playtika.com/careers/security-it/"),
    ("Forter", "https://www.forter.com/job-opportunities/"),
    ("Rapyd", "https://www.rapyd.net/company/careers-search/?location=israel"),
    ("Flytrex", "https://www.flytrex.com/careers/"),
    ("Bringg", "https://www.bringg.com/company/careers/"),
    ("Via", "https://ridewithvia.com/careers/jobs"),
    ("Buildots", "https://www.buildots.com/careers/"),
    ("Optibus", "https://optibus.com/company/careers/jobs/"),
    ("Cloudinary", "https://cloudinary.com/careers/jobs"),
    ("RapidAPI", "https://rapidapi.com/company/careers/#join"),
    ("Sisense", "https://www.sisense.com/about/careers/#job-positions-table"),
    ("Papaya Global", "https://www.papayaglobal.com/careers/"),
    ("AppsFlyer", "https://careers.appsflyer.com/#careersOps"),
    ("IronSource", "https://unity.com/careers/positions?location=tel-aviv"),
    ("Riskified", "https://www.riskified.com/careers/#positions"),
    ("Weka", "https://www.weka.io/company/careers/#career-position"),
    ("Cheq", "https://www.cheq.ai/careers"),
    ("PlainID", "https://www.plainid.com/work-with-us/"),
    ("Pipl", "https://www.comeet.com/jobs/pipl/22.008"),
    ("Syqe Medical", "https://syqe.com/careers/"),
    ("Fabric", "https://getfabric.com/careers"),
    ("Scopio Labs", "https://scopiolabs.com/careers/?utm_term=scopio%20digital%20morphology&utm_campaign=Search+All-in+28/5&utm_source=adwords&utm_medium=ppc&hsa_acc=3374207472&hsa_cam=22614349834&hsa_grp=177107399461&hsa_ad=754951383067&hsa_src=g&hsa_tgt=kwd-2423818567330&hsa_kw=scopio%20digital%20morphology&hsa_mt=b&hsa_net=adwords&hsa_ver=3&gad_source=1&gad_campaignid=22614349834&gbraid=0AAAAA-GPCAupAhurLnE9-JhwivL6REiDB&gclid=CjwKCAjw6ZTCBhBOEiwAqfwJd5TR5TDCz62Wh39g69UhngR0L_zCenQ45G3xefpiWC9aQ-ycSD0rdRoC5eAQAvD_BwE"),
    ("Remilk", "https://www.remilk.com/careers"),
    ("Upstream Security", "https://www.upstream.auto/careers/"),
    ("Verbit", "https://verbit.ai/careers-listing/"),
    ("Jfrog", "https://join.jfrog.com/positions/?gh_office=25868"),
    ("Nvidia", "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?locationHierarchy1=2fcb99c455831013ea52bbe14cf9326c"),
    ("Cato Networks", "https://www.catonetworks.com/careers/?location=Israel%3B+Tel+Aviv+District%2C+Israel"),
    ("intenthq", "https://intenthq.teamtailor.com/jobs"),
    ("Cellebrite", "https://cellebrite.com/en/about/careers/positions/?comeet_cat=israel&comeet_all=all"),
    ("Hailo", "https://hailo.ai/company-overview/careers/"),
    ("Bizzabo", "https://www.bizzabo.com/careers#openings"),
    ("Vayyar", "https://vayyar.com/careers/#jobs"),
    ("Vanti", "https://tray.ai/careers"),
    ("Wiliot", "https://www.wiliot.com/careers"),
    ("Trigo", "https://www.trigoretail.com/careers/"),
    ("Lightico", "https://www.lightico.com/careers/"),
    ("Voyantis", "https://www.voyantis.ai/careers#positions"),
    ("C2A Security", "https://www.c2a-sec.com/careers/"),
    ("Hibob", "https://www.hibob.com/careers/"),
    ("Lusha", "https://www.lusha.com/careers/#careers"),
    ("OpenWeb", "https://www.openweb.com/careers/#join"),
    ("Mine", "https://mine.breezy.hr/"),
    ("AccessiBe", "https://www.comeet.com/jobs/accessibe/D5.00B"),
    ("Jiga", "https://www.ycombinator.com/companies/jiga/jobs/"),
    ("Varos", "https://www.ycombinator.com/companies/varos"),
    ("Elevate", "https://elevate.com/careers"),
    ("Diversion", "https://diversion.dev/careers"),
    ("Vimeo", "https://vimeo.com/jobs"),
    ("Pendo", "https://www.pendo.io/careers/"),
    ("Unity", "https://careers.unity.com/"),
    ("Vonage", "https://careers.vonage.com/"),
    ("ZoomInfo", "https://www.zoominfo.com/about/careers"),
    ("Datadog", "https://www.datadoghq.com/careers/"),
    ("Rubrik", "https://www.rubrik.com/company/careers"),
    ("MongoDB", "https://www.mongodb.com/careers"),
    ("Microsoft", "https://careers.microsoft.com/v2/global/en/locations/israel.html"),
    ("Intuit", "https://www.intuit.com/careers/locations/israel/"),
    ("JPMorgan Chase", "https://careers.jpmorgan.com/global/en/students/campaign/TechCareersIsrael"),
    ("IBM", "https://www.ibm.com/planetwide/il/"),
    ("Apple", "https://www.apple.com/jobs/il/"),
    ("Facebook", "https://www.facebookcareers.com/locations/israel/"),
    ("Nvidia", "https://www.nvidia.com/en-us/about-nvidia/careers/"),
    ("Oracle", "https://www.oracle.com/corporate/careers/"),
    ("Salesforce", "https://www.salesforce.com/company/careers/"),
    ("Cisco", "https://jobs.cisco.com/locations/israel"),
    ("Intel", "https://jobs.intel.com/en/location/israel-jobs/375/294640/2"),
    ("SAP", "https://jobs.sap.com/location/Israel/1776/6252001-6254928/1"),
    ("Dell", "https://jobs.dell.com/en/location/israel-jobs/375/294640/2"),
    ("HP", "https://jobs.hp.com/en/location/israel-jobs/375/294640/2"),
    ("Samsung", "https://www.samsung.com/us/careers/"),
    ("LG", "https://www.lg.com/global/careers"),
    ("Sony", "https://www.sony.net/SonyInfo/Careers/"),
    ("Qualcomm", "https://www.qualcomm.com/company/careers"),
    ("Broadcom", "https://www.broadcom.com/company/careers"),
    ("Texas Instruments", "https://careers.ti.com/"),
    ("Western Digital", "https://jobs.westerndigital.com/"),
    ("Seagate", "https://www.seagate.com/jobs/"),
    ("Micron", "https://www.micron.com/careers"),
    ("Analog Devices", "https://www.analog.com/en/about-adi/careers.html"),
    ("Marvell", "https://www.marvell.com/company/careers.html"),
    ("Skyworks", "https://www.skyworksinc.com/en/Careers"),
    ("Infineon", "https://www.infineon.com/cms/en/careers/"),
    ("STMicroelectronics", "https://www.st.com/content/st_com/en/about/careers.html"),
    ("NXP", "https://www.nxp.com/company/about-nxp/careers"),
    ("ON Semiconductor", "https://www.onsemi.com/company/careers"),
    ("Renesas", "https://www.renesas.com/us/en/about/careers"),
    ("Cypress", "https://www.cypress.com/about-cypress/careers"),
    ("Xilinx", "https://www.xilinx.com/about/careers.html"),
    ("Altera", "https://altera.wd1.myworkdayjobs.com/Altera"),
    ("Lattice", "https://www.latticesemi.com/en/About/Careers"),
    ("Microchip", "https://www.microchip.com/about/careers"),
    ("Maxim Integrated", "https://www.maximintegrated.com/en/aboutus/careers.html"),
    ("Dialog Semiconductor", "https://www.dialog-semiconductor.com/careers"),
    ("Silicon Labs", "https://www.silabs.com/about-us/careers"),
    ("Ambarella", "https://www.ambarella.com/about/careers/"),
    ("MediaTek", "https://www.mediatek.com/about/careers"),
    ("Realtek", "https://www.realtek.com/en/about-realtek/career"),
    ("HiSilicon", "https://www.hisilicon.com/en/careers"),
    ("Spreadtrum", "https://www.spreadtrum.com/en/careers"),
    ("Rockchip", "https://www.rock-chips.com/a/en/about/careers/"),
    ("Allwinner", "https://www.allwinnertech.com/index.php?c=about&a=careers"),
    ("Amlogic", "https://www.amlogic.com/about/careers"),
    ("Actions Semiconductor", "http://www.actions-semi.com/en/about/careers"),
    ("Leadcore", "http://www.leadcoretech.com/en/about/careers"),
    ("Unisoc", "https://www.unisoc.com/en/about/careers"),
    ("ZTE", "https://www.zte.com.cn/global/careers"),
    ("Huawei", "https://career.huawei.com/reccampportal/portal5/index.html"),
    ("Lenovo", "https://www.lenovo.com/us/en/about/careers/"),
    ("Acer", "https://www.acer.com/ac/en/US/content/careers"),
    ("Asus", "https://www.asus.com/us/About_ASUS/Careers/"),
    ("MSI", "https://www.msi.com/about/careers"),
    ("Gigabyte", "https://www.gigabyte.com/About/Careers"),
    ("Biostar", "https://www.biostar.com.tw/app/en/about/career.php"),
    ("EVGA", "https://www.evga.com/company/careers/"),
    ("Zotac", "https://www.zotac.com/us/page/careers"),
    ("Palit", "https://www.palit.com/palit/about_careers.php?lang=en"),
    ("Inno3D", "https://www.inno3d.com/about/careers"),
    ("Gainward", "https://www.gainward.com/main/about.php?lang=en"),
    ("Colorful", "https://en.colorful.cn/about/careers"),
    ("Sapphire", "https://www.sapphiretech.com/en/about/careers"),
    ("PowerColor", "https://www.powercolor.com/about/careers"),
    ("XFX", "https://www.xfxforce.com/en-us/about/careers"),
    ("HIS", "https://www.hisdigital.com/un/about.shtml"),
    ("VisionTek", "https://www.visiontek.com/about/careers"),
    ("Diamond Multimedia", "https://www.diamondmm.com/about/careers"),
    ("Matrox", "https://www.matrox.com/en/corporate/careers"),
    ("ECS", "https://www.ecs.com.tw/about/careers"),
    ("Shuttle", "https://global.shuttle.com/about/careers"),
    ("Foxconn", "https://www.foxconn.com/en-us/careers"),
    ("Pegatron", "https://www.pegatroncorp.com/about/careers"),
    ("Quanta", "https://www.quantatw.com/Quanta/english/careers.aspx"),
    ("Compal", "https://www.compal.com/about/careers"),
    ("Wistron", "https://www.wistron.com/about/careers"),
    ("Inventec", "https://www.inventec.com/en/about/careers"),
    ("Flex", "https://flex.com/careers"),
    ("Jabil", "https://www.jabil.com/careers.html"),
    ("Sanmina", "https://www.sanmina.com/careers/"),
    ("Celestica", "https://www.celestica.com/careers/"),
    ("Benchmark Electronics", "https://www.bench.com/careers"),
    ("Plexus", "https://www.plexus.com/en-us/careers"),
    ("TTM Technologies", "https://www.ttm.com/careers"),
    ("Venture Corporation", "https://www.venture.com.sg/careers"),
    ("UMC", "https://www.umc.com/english/careers"),
    ("SMIC", "https://www.smics.com/en/site/careers"),
    ("GlobalFoundries", "https://www.globalfoundries.com/about-us/careers"),
    ("TSMC", "https://www.tsmc.com/english/careers"),
    ("Samsung Foundry", "https://www.samsung.com/semiconductor/foundry/careers/"),
    ("Tower Semiconductor", "https://www.towersemi.com/careers/"),
    ("X-Fab", "https://www.xfab.com/career/"),
    ("Vanguard International Semiconductor", "https://www.vis.com.tw/en/careers"),
    ("Hua Hong Semiconductor", "https://www.huahonggrace.com/en/careers"),
    ("DB HiTek", "https://www.dbhitek.com/eng/careers"),
    ("Magnachip", "https://www.magnachip.com/company/careers/"),
    ("SK Hynix", "https://www.skhynix.com/eng/careers/index.jsp"),
    ("Micron", "https://www.micron.com/careers"),
    ("Kioxia", "https://www.kioxia.com/en-jp/about/careers.html"),
    ("Western Digital", "https://jobs.westerndigital.com/"),
    ("Seagate", "https://www.seagate.com/jobs/")

]

# Insert them into the database
for name, url in websites:
    cursor.execute("INSERT INTO websites (name, url) VALUES (?, ?)", (name, url))

# Save and close
conn.commit()
conn.close()

print("Websites added successfully.")
